// ==UserScript==
// @name          Bangumi.tv夜间模式
// @namespace     http://userstyles.org
// @description	  本CSS样式为Bangumi.tv的夜间模式，为了方便夜间使用而编写的。    
// @author        InfinityLoop
// @homepage      https://userstyles.org/styles/139310
// @include       http://bangumi.tv/*
// @include       https://bangumi.tv/*
// @include       http://*.bangumi.tv/*
// @include       https://*.bangumi.tv/*
// @include       http://bgm.tv/*
// @include       https://bgm.tv/*
// @include       http://*.bgm.tv/*
// @include       https://*.bgm.tv/*
// @include       http://chii.in/*
// @include       https://chii.in/*
// @include       http://*.chii.in/*
// @include       https://*.chii.in/*
// @run-at        document-start
// @version       0.20181222131636
// ==/UserScript==
(function() {var css = [
	"body {",
	"	background: #222222;",
	"}",
	"/*************首页部分*************/",
	"#introWrapper {",
	"	background: #222222;",
	"}",
	"",
	"/*头部*/",
	"#headerNeue2 {",
	"	background: black;",
	"}",
	"",
	"/*顶部菜单栏的字体颜色*/",
	"#navNeue2 #navMenuNeue li a.top:hover, #navNeue2 #navMenuNeue li a.top_lite:hover, #navNeue2 #navMenuNeue li:hover a.top, #navNeue2 #navMenuNeue li.sfhover a.top, #navNeue2 #navMenuNeue li a.focus:hover {",
	"	color: white;",
	"}",
	"",
	"/*背景黑色*/",
	"body.bangumiNeue {",
	"	background: #222222;",
	"}",
	"/*点格子时弹出的block背景色*/",
	".cluetip-default #cluetip-inner {",
	"	background: #373737;",
	"}",
	"",
	"/*点格子界面*/",
	".jspContainer {",
	"	background: #222;",
	"}",
	"",
	"#prgManagerHeader {",
	"	background: #222222;",
	"}",
	"",
	"#prgManagerHeader ul.categoryTab li a {",
	"	color: #FFFFFF;",
	"}",
	"",
	"#prgManagerHeader ul.categoryTab li a:hover{",
	"	background: #000000;",
	"}",
	"",
	"#cloumnSubjectInfo .tinyMode {",
	"	background: #222222;",
	"}",
	"",
	"#cloumnSubjectInfo {",
	"	background: black;",
	"}",
	"",
	"#cloumnSubjectInfo .tinyMode div.tinyHeader a, ul#prgSubjectList.full li a.title {",
	"	color: #f09199;",
	"}",
	"",
	"ul#prgSubjectList.list li a.title {",
	"	background: #222222;",
	"}",
	"#cloumnSubjectInfo div.moreEp {",
	"	background: #222222;",
	"}",
	"ul#prgSubjectList.full li {",
	"	background: #222222;",
	"}",
	"ul#prgSubjectList.list li.onAir, ul#prgSubjectList.full li.onAir  {",
	"	background-color: #333333;",
	"}",
	"",
	"#cloumnSubjectInfo div.header {",
	"	background: none;",
	"}",
	"ul#prgSubjectList.list li a.title {",
	"	color: #b3b3b3;",
	"}",
	"#prgManagerMain.tinyModeWrapper #cloumnSubjectInfo",
	".infoWrapper_book{",
	"	background: #222222;",
	"}",
	"ul#prgSubjectList.grid {",
	"	background: #222222;",
	"}",
	"",
	"/*修改动画图标为圆形*/",
	"img.grid {",
	"	border-radius: 26px;",
	"}",
	"",
	"/*栏目背景颜色*/",
	"ul.sideTpcList li .inner {",
	"	background: #222222;		",
	"}",
	".line_odd {",
	"	background-color: black;	",
	"}",
	".line_even {",
	"	background-color: #222222;	",
	"}",
	"/**/",
	".line_odd {",
	"    background-color: #222;   ",
	"}",
	"/*底部的关于我们部分*/",
	"div#footer ul#footerLinks {",
	"	background: #1c1c1c;",
	"}",
	"",
	"/*BGM客户端*/",
	"div.SidePanelMini {",
	"	background: #222222;",
	"}",
	"",
	"/*************个人主页部分*************/",
	".columns {",
	"	background: #222222;",
	"}",
	"#wrapperNeue{",
	"	background: #222222;",
	"}",
	"",
	"/*头像菜单栏部分颜色*/",
	"#headerProfile div.subjectNav {",
	"	background: #222222;",
	"}",
	"",
	"#headerProfile .headerContainer {",
	"	background: #2f2f2f;",
	"}",
	"",
	"",
	"/*自我介绍背景颜色*/",
	"blockquote.intro {",
	"	background: #414141;",
	"}",
	"",
	"blockquote.intro div.bio {",
	"	color: #dddddd;",
	"}",
	"",
	"/*调整字体颜色和高亮*/",
	"ul.coversSmall li > a {",
	"	color: #a7a7a7;",
	"}",
	"",
	"ul.coversSmall li > a:hover {",
	"	color: #f09199;",
	"}",
	"",
	"/*调整右边栏颜色*/",
	"div.SidePanel, div.SidePanelLow {",
	"	background: #222222;	",
	"}",
	"div.SidePanel h2, div.SidePanelLow h2 {",
	"	color: #f09199;	",
	"	text-shadow: black 1px 1px 0px;",
	"}",
	"",
	"/*RSS订阅块颜色*/",
	"div.menu_inner {",
	"	background: #222222;",
	"}",
	"",
	"/*调整底部margin*/",
	"div#footer {",
	"	margin: 0 0 0 0;	",
	"}",
	"",
	"",
	"/*************帖子部分内容调整*************/",
	"/*标题*/",
	"div#pageHeader h1 {",
	"	color: #cccccc;",
	"}",
	"",
	"/*主帖*/",
	"div.postTopic div.inner div.topic_content {",
	"	color: #a0a0a0;",
	"}",
	"/*回复背景颜色*/",
	"div.light_even {",
	"	background: #222222;",
	"	color: #a0a0a0;",
	"}",
	"div.light_odd {",
	"	background: #313131;",
	"	color: #a0a0a0;",
	"}",
	"",
	"/*************条目内容颜色*************/",
	"/*顶部菜单栏*/",
	".subjectNav .navTabs {",
	"	background: #373737;",
	"}",
	"/*顶部标题*/",
	"#headerSubject h1 a{",
	"	color: #cccccc;",
	"}",
	"/*右侧收藏盒子*/",
	"div.SidePanel, div.SidePanelLow {",
	"	color: #cccccc;",
	"}",
	".horizontalChart li .label {",
	"	color: #cccccc;",
	"}",
	"#ChartWarpper .chart_desc {",
	"	background-color: #555555;",
	"}",
	"",
	"",
	"/*介绍字体颜色*/",
	"div#subject_detail div#subject_summary {",
	"	color: #aaaaaa;",
	"}",
	"",
	"/*tip字体颜色*/",
	".tip {",
	"	color: #d0d0d0;",
	"}",
	"",
	"ul#infobox li {",
	"	color: #aaaaaa;",
	"}",
	"",
	"/*边条减细*/",
	"div.section_line {",
	"	height: 1px;",
	"}",
	"",
	"/*评分栏背景色*/",
	"#ChartWarpper {",
	"	background-color: #373737;",
	"}",
	"",
	"/*Tag栏背景*/",
	"div.subject_tag_section {",
	"	background: #373737;",
	"}",
	"",
	"/*编辑者信息背景*/",
	"div.infobox .modifyTool {",
	"	background: #373737;",
	"}",
	"",
	"/*角色介绍*/",
	"ul.browserMedium strong a {",
	"	color: #aaaaaa;",
	"}",
	"",
	"/*评论版面字体颜色*/",
	"#entry_list div.item .content {",
	"	color: #aaaaaa;",
	"}",
	"",
	"/*讨论版*/",
	"table td.even {",
	"	background-color: #373737;",
	"}",
	"",
	"/*个人收藏页面顶部*/",
	".subjectNav .navSubTabs {",
	"	background: #373737;",
	"}",
	"",
	"/*中列表浏览模式偶数项目背景*/",
	"ul.browserFull li.even {",
	"	background: #333333;",
	"}",
	"/*小列表浏览模式偶数项目背景*/",
	"ul.browserList li.even {",
	"	background: #333333;",
	"}",
	"",
	".navSubTabsWrapper {",
	"	background: none;",
	"}",
	"",
	"/*tag标签的底色*/",
	"div.subject_tag_section a.l {",
	"    background: #373737;",
	"}",
	"",
	"/*评论气泡*/",
	"#comment_box .text_main_even .text, #comment_box .text_main_odd .text, #comment_box .text_pm {",
	"    background: #333;",
	"}",
	"div#comment_box .text {",
	"	color: #cccccc;",
	"}",
	"/*评论气泡里的星星*/",
	".starsinfo {",
	"    background: transparent url(https://i.loli.net/2017/10/02/59d22ca89c4e1.png) no-repeat;",
	"}",
	".sstars1 {",
	"    background-position: right -52px;",
	"}",
	".sstars2 {",
	"    background-position: left -52px;",
	"}",
	".sstars3 {",
	"    background-position: right -39px;",
	"}",
	".sstars4 {",
	"    background-position: left -39px;",
	"}",
	".sstars5 {",
	"    background-position: right -26px;",
	"}",
	".sstars6 {",
	"    background-position: left -26px;",
	"}",
	".sstars7 {",
	"    background-position: right -13px;",
	"}",
	".sstars8 {",
	"    background-position: left -13px;",
	"}",
	".sstars9 {",
	"    background-position: right 0px;",
	"}",
	".sstars10 {",
	"    background-position: left 0px;",
	"}",
	"/*************章节*************/",
	".epDesc {",
	"	color: #7a7a7a;	",
	"}",
	"ul.sideEpList li.even {",
	"	background: #333333;",
	"}",
	"#headerSubject div.subjectNav {",
	"	background: #373737;",
	"}",
	"/*帖子高亮回复*/",
	"div.reply_highlight {",
	"	background: #373737;",
	"}",
	"",
	"/*中央主页时间线*/",
	"#columnTimelineInnerB {",
	"	background-color: #222222;",
	"}",
	"",
	"#columnTimelineInnerB div.TsukkmiBox {",
	"	background: #373737;",
	"}",
	"#columnTimelineInnerWrapper ul.timelineTabs {",
	"	background: #373737;",
	"}",
	"ul.timelineTabs li a:hover {",
	"	color: white;",
	"}",
	"",
	"/*消息提示*/",
	"#TB_iframeContent {",
	"	background: #222222;",
	"}",
	"",
	"/*************小组页面*************/",
	"/*小组介绍*/",
	"h1.SecondaryNavTitle {",
	"	color: #aaaaaa;",
	"}",
	"",
	"div.grp_box {",
	"	background: #373737;",
	"}",
	"",
	"/*帖子列表*/",
	"table.topic_list th {",
	"	background: #373737;",
	"}",
	"",
	"table.topic_list tr.even {",
	"	background: #373737;",
	"}",
	".topic_list td a {",
	"	color: #cccccc;",
	"}",
	".topic_list td a:hover {",
	"	color: #02A3FB;",
	"}",
	"",
	"/*右边小组列表名字*/",
	"ul.groupsSmall li div.inner a {",
	"	color: #cccccc;",
	"}",
	"ul.groupsSmall li div.inner a:hover {",
	"	color: #02A3FB;",
	"}",
	"/*顶部小组列表名字*/",
	"ul.groupsLarge li a {",
	"	color: #cccccc;",
	"}",
	"ul.groupsLarge li a:hover {",
	"	color: #02A3FB;",
	"}",
	"/*小组*/",
	"#wrapperNeue #header h1 {",
	"	color: white;",
	"}",
	"",
	"",
	"/*好友页面的名字*/",
	"ul.usersMedium strong a{",
	"	color: #aaaaaa;",
	"}",
	"",
	"/*日志主帖颜色*/",
	"div#entry_content {",
	"	color: #cccccc;",
	"}",
	"",
	"/*************条目的评分人评价等界面*************/",
	"/*评价用户名*/",
	"ul.usersLarge strong a {",
	"	color: white;",
	"}",
	"/*评价内容*/",
	"ul.usersLarge {",
	"	color: #cccccc;",
	"}",
	"",
	"/*右边信息的字体颜色*/",
	"div.menu_inner a {",
	"	color: #cccccc;",
	"}",
	"div.menu_inner a:hover{",
	"	color: #02A3FB;",
	"}",
	"",
	"/*************电波提醒*************/",
	"#columnNotifyA div.even {",
	"    background-color: #373737;",
	"}",
	"",
	"/*修改弹出框的底色*/",
	"#TB_ajaxContent {",
	"    background:#222222;",
	"}",
	"/*鼠标划过[mask]文字自动显示*/",
	"span[style=\"background-color:#555;color:#555;border:1px solid #555;\"]:hover {",
	"    color: #CCCCCC !important;",
	"}",
	"/*评论框底色*/",
	"textarea.reply, textarea.quick:focus, textarea.reply:focus, input.inputtext, input.inputtext:focus {",
	"    background-color: #222222;   ",
	"    color: #cccccc;",
	"}",
	"/*评论标题\"请填写标题\"，\"请填写回复内容\"字体颜色*/",
	"table.settings td label, label.error {",
	"    color: #f09199;",
	"}",
	"/*about页面*/",
	"div.about_text {",
	"    color: #cccccc;",
	"}",
	"small {",
	"    color: white;",
	"}",
	"",
	"/*首页的文字阴影*/",
	"#cloumnSubjectInfo div.header h3 {",
	"    text-shadow: none;",
	"}",
	"#cloumnSubjectInfo, #cloumnSubjectInfo .blockMode {",
	"    background-color: #222;",
	"}",
	"",
	"/*************人物*************/",
	"#columnChlCrtB {",
	"    background-color: #222;",
	"}",
	"#headerSubject h1 {",
	"    color: white;   ",
	"}",
	"",
	"/*频道上面区域的说明文字颜色*/",
	"#news_list div.item .content {",
	"    color: #aaa;   ",
	"}",
	"",
	"/*条目筛选右侧低栏*/",
	"#columnSubjectBrowserB .sideInner {",
	"    background: #333;   ",
	"}",
	"/*条目筛选右侧标题栏*/",
	"#columnSubjectBrowserB .sideInner h2 {",
	"    background: #222",
	"}"
].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node);
	} else {
		// no head yet, stick it whereever
		document.documentElement.appendChild(node);
	}
}
})();
